# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-08 05:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20161008_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='accounts.Option')),
            ],
        ),
        migrations.CreateModel(
            name='Stapl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_thumb',
        ),
        migrations.RemoveField(
            model_name='user',
            name='teaches',
        ),
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.TextField(default='0', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='class_identifier',
            field=models.CharField(default='79a60c3', max_length=7, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='0', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='teaches', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default='0', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='0', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='accounts.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='back',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='front',
            field=models.TextField(max_length=100),
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('stapl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Stapl')),
                ('name', models.CharField(max_length=20)),
            ],
            bases=('accounts.stapl',),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('stapl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Stapl')),
                ('text', models.TextField(max_length=10000)),
            ],
            bases=('accounts.stapl',),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('stapl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.Stapl')),
                ('active', models.BooleanField(default=True)),
            ],
            bases=('accounts.stapl',),
        ),
        migrations.AddField(
            model_name='stapl',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stapls', to='accounts.Chapter'),
        ),
        migrations.AddField(
            model_name='stapl',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stapls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='stapl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.Stapl'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='accounts.Poll'),
        ),
        migrations.AddField(
            model_name='option',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='accounts.Poll'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='deck',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='accounts.Deck'),
            preserve_default=False,
        ),
    ]
