# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-08 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20161008_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_identifier',
            field=models.CharField(default='e6755b4', max_length=7, unique=True),
        ),
    ]
