# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-08 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20161008_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_identifier',
            field=models.CharField(default='c1e422e', max_length=7, unique=True),
        ),
    ]
