# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-08 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20161008_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_identifier',
            field=models.CharField(default='d93211d', max_length=7, unique=True),
        ),
    ]
