# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-08 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20161008_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='name',
            field=models.CharField(default='chapter 1', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='class_identifier',
            field=models.CharField(default='6c6b895', max_length=7, unique=True),
        ),
    ]
