# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-08 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20161008_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_identifier',
            field=models.CharField(default='639d2c2', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='accounts.Deck'),
        ),
    ]
