# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-08 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20161008_1104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Answer',
        ),
        migrations.AlterField(
            model_name='course',
            name='class_identifier',
            field=models.CharField(default='414a101', max_length=7, unique=True),
        ),
    ]
