# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-08 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20161008_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='text',
        ),
        migrations.AddField(
            model_name='note',
            name='filepath',
            field=models.FileField(default='badfile', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='class_identifier',
            field=models.CharField(default='d22f251', max_length=7, unique=True),
        ),
    ]
