# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-08 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20161008_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_identifier',
            field=models.CharField(default='4ace842', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='filepath',
            field=models.FilePathField(),
        ),
    ]
