# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-08 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20161008_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='qrcode',
            field=models.FilePathField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_identifier',
            field=models.CharField(default='f275ccd', max_length=7, unique=True),
        ),
    ]
